name: checklist
description: "LuPo Forms Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smb_connect: ^0.0.9
  path: ^1.8.3
  json_annotation: ^4.8.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  uuid: ^4.3.3
  http: ^1.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48


flutter:
  uses-material-design: true

  assets:
    - assets/images/LOGO LuPo_transparent.png
